# Generated by Django 2.2.4 on 2019-09-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='short_bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
