version: '3.7'

services:
  web:
    build: .
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY
      - DEBUG
      - ADMIN_URL
      - SENDGRID_USERNAME
      - SENDGRID_PASSWORD
      - STRIPE_TEST_PUBLISHABLE_KEY
      - STRIPE_TEST_SECRET_KEY
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn webapp.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
