# Generated by Django 2.2.3 on 2019-08-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190809_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='assets/images/hello_cover.png', upload_to='covers/'),
        ),
    ]
