# Generated by Django 2.2.3 on 2019-08-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190810_0354'),
        ('books', '0003_book_cover'),
    ]

    operations = [
    ]
