# Generated by Django 2.2.4 on 2019-08-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190821_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='images/hello_cover.png', upload_to='covers/'),
        ),
    ]
