# Generated by Django 2.2.4 on 2019-08-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190828_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/django_restful.jpg', upload_to='covers/'),
        ),
    ]
