# Generated by Django 2.2.4 on 2019-09-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190901_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_img',
            field=models.ImageField(default='blog_images/default_header.jpeg', upload_to='blog_images/'),
        ),
    ]
