# Generated by Django 2.2.4 on 2019-09-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_header_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_img',
            field=models.ImageField(blank=True, default='blog_images/default_header.jpeg', null=True, upload_to='blog_images'),
        ),
    ]
