# Generated by Django 2.2.4 on 2019-09-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190918_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_img',
            field=models.ImageField(default='blog_images/default_header.jpeg', upload_to='blog_images'),
        ),
    ]
